### PR TITLE
fix CI checks

### PR DESCRIPTION
**Pull request by AlhassenSabeeh**
Adding tow files to the main branch.

### CODE REVIEW

**Comment by GhyathSAhmed** [comment]
i will look into the rest of the CI checks

**Review by GhyathSAhmed — APPROVED** [review]
i looked up the CI checks and modified the needed files to pass it!!
great job updating the solutions and tests folders with the (__init__) files

**Review by GhyathSAhmed — APPROVED** [review]

**Comment by AlhassenSabeeh** [comment]
Amazing!!

**Review by Adamx090 — APPROVED** [review]
Impressive work @GhyathSAhmed , that's a lot of fixes you did there. Everything look great, well done.

**Pull request merged**
